namespace PowerUp.Entities
{
  public enum EntitySourceType
  {
    /// <summary>
    /// Included in original game
    /// </summary>
    Base,
    /// <summary>
    /// Imported from game save file
    /// </summary>
    Imported,
    /// <summary>
    /// Generated by PowerUp, tied to specific identifying information (ie. Year, Name, etc.).
    /// Generated Players' properties can be edited, but their identifying information must remain the same.
    /// </summary>
    Generated,
    /// <summary>
    /// Updated through app, no longer tied to specific identifying information
    /// </summary>
    Custom
  }
}
