namespace PowerUp.GameSave.Objects.Players
{
  public interface IGSPlayer
  {
    short? AggressiveOrCautiousBaseStealer { get; set; }
    short? AggressiveOrPatientHitter { get; set; }
    ushort? ArmStrength { get; set; }
    short? BaseRunning { get; set; }
    ushort? BasesLoadedHitter { get; set; }
    ushort? Bat { get; set; }
    ushort? BattingAveragePoints { get; set; }
    ushort? BattingForm { get; set; }
    ushort? BattingSide { get; set; }
    ushort? BirthDay { get; set; }
    ushort? BirthMonth { get; set; }
    ushort? BirthYear { get; set; }
    ushort? Bunting { get; set; }
    bool? CanBarehandCatch { get; set; }
    bool? CanSpiderCatch { get; set; }
    ushort? CatcherCapability { get; set; }
    ushort? Catching { get; set; }
    ushort? CenterFieldCapability { get; set; }
    short? ClutchHitter { get; set; }
    ushort? Contact { get; set; }
    ushort? Control { get; set; }
    ushort? Curve1Movement { get; set; }
    ushort? Curve1Type { get; set; }
    ushort? Curve2Movement { get; set; }
    ushort? Curve2Type { get; set; }
    bool? DoctorK { get; set; }
    short? Durability { get; set; }
    ushort? EarnedRunAverage { get; set; }
    ushort? EarringColor { get; set; }
    ushort? EarringSide { get; set; }
    byte[]? EmptyPlayerBytes { get; set; }
    ushort? ErrorResistance { get; set; }
    ushort? EyewearColor { get; set; }
    ushort? EyewearType { get; set; }
    ushort? Face { get; set; }
    ushort? FacialHair { get; set; }
    ushort? FacialHairColor { get; set; }
    short? FastballLife { get; set; }
    ushort? Fielding { get; set; }
    ushort? FirstBaseCapability { get; set; }
    string? FirstName { get; set; }
    ushort? Fork1Movement { get; set; }
    ushort? Fork1Type { get; set; }
    ushort? Fork2Movement { get; set; }
    ushort? Fork2Type { get; set; }
    ushort? FourSeamMovement { get; set; }
    ushort? FourSeamType { get; set; }
    ushort? Glove { get; set; }
    bool? GoodDelivery { get; set; }
    bool? GoodLowPitch { get; set; }
    short? GoodOrPoorDayGame { get; set; }
    short? GoodOrPoorRain { get; set; }
    bool? GoodPickoff { get; set; }
    short? GroundBallOrFlyBallPitcher { get; set; }
    bool? Gyroball { get; set; }
    ushort? Hair { get; set; }
    ushort? HairColor { get; set; }
    bool? HasCannonArm { get; set; }
    bool? HasGoodPace { get; set; }
    bool? HasGoodReflexes { get; set; }
    bool? HasPokerFace { get; set; }
    short? HittingConsistency { get; set; }
    short? HittingVersusLefty1 { get; set; }
    short? HittingVersusLefty2 { get; set; }
    ushort? HomeRuns { get; set; }
    ushort? HotZoneDown { get; set; }
    ushort? HotZoneDownAndAway { get; set; }
    ushort? HotZoneDownAndIn { get; set; }
    ushort? HotZoneMiddle { get; set; }
    ushort? HotZoneMiddleAway { get; set; }
    ushort? HotZoneMiddleIn { get; set; }
    ushort? HotZoneUp { get; set; }
    ushort? HotZoneUpAndAway { get; set; }
    ushort? HotZoneUpAndIn { get; set; }
    ushort? InfieldHitter { get; set; }
    bool? IsAggressiveBaserunner { get; set; }
    bool? IsAggressiveFielder { get; set; }
    bool? IsBackToBackHitter { get; set; }
    bool? IsBattler { get; set; }
    bool? IsChokeArtist { get; set; }
    bool? IsCloser { get; set; }
    bool? IsContactHitter { get; set; }
    bool? IsEdited { get; set; }
    bool? IsErrorProne { get; set; }
    bool? IsFirstballHitter { get; set; }
    bool? IsFreeSwinger { get; set; }
    bool? IsGoldGlover { get; set; }
    bool? IsGoodBlocker { get; set; }
    bool? IsGoodPinchHitter { get; set; }
    bool? IsHotHead { get; set; }
    bool? IsHotHitter { get; set; }
    bool? IsIntimidatingHitter { get; set; }
    bool? IsIntimidatingPitcher { get; set; }
    bool? IsPivotMan { get; set; }
    bool? IsPowerHitter { get; set; }
    bool? IsPullHitter { get; set; }
    bool? IsPushHitter { get; set; }
    bool? IsRallyHitter { get; set; }
    bool? IsRefinedHitter { get; set; }
    bool? IsReliever { get; set; }
    bool? IsSandbag { get; set; }
    bool? IsSlowStarter { get; set; }
    bool? IsSparkplug { get; set; }
    bool? IsSprayHitter { get; set; }
    bool? IsStar { get; set; }
    bool? IsStarter { get; set; }
    bool? IsStarterFinisher { get; set; }
    bool? IsTableSetter { get; set; }
    bool? IsToughOut { get; set; }
    bool? IsToughRunner { get; set; }
    bool? IsTrashTalker { get; set; }
    bool? IsWalkProne { get; set; }
    string? LastName { get; set; }
    ushort? LeftFieldCapability { get; set; }
    ushort? LeftWristband { get; set; }
    short? Luck { get; set; }
    short? Morale { get; set; }
    ushort? PitcherCapability { get; set; }
    short? PitchingConsistency { get; set; }
    ushort? PitchingForm { get; set; }
    short? PitchingVersusLefty { get; set; }
    ushort? PlayerNumber { get; set; }
    ushort? PlayerNumberNumberOfDigits { get; set; }
    short? Poise { get; set; }
    bool? PoorVersusRunner { get; set; }
    ushort? Power { get; set; }
    short? PowerOrBreakingBallPitcher { get; set; }
    ushort? PowerProsId { get; set; }
    ushort? PowerProsTeamId { get; set; }
    ushort? PrimaryPosition { get; set; }
    short? Recovery { get; set; }
    short? Release { get; set; }
    ushort? RightFieldCapability { get; set; }
    ushort? RightWristband { get; set; }
    ushort? RunsBattedIn { get; set; }
    ushort? RunSpeed { get; set; }
    short? SafeOrFatPitch { get; set; }
    string? SavedName { get; set; }
    ushort? SecondBaseCapability { get; set; }
    ushort? ShortstopCapability { get; set; }
    bool? ShuttoSpin { get; set; }
    ushort? Sinker1Movement { get; set; }
    ushort? Sinker1Type { get; set; }
    ushort? Sinker2Movement { get; set; }
    ushort? Sinker2Type { get; set; }
    ushort? SinkingFastball1Movement { get; set; }
    ushort? SinkingFastball1Type { get; set; }
    ushort? SinkingFastball2Movement { get; set; }
    ushort? SinkingFastball2Type { get; set; }
    ushort? SkinAndEyes { get; set; }
    ushort? Slider1Movement { get; set; }
    ushort? Slider1Type { get; set; }
    ushort? Slider2Movement { get; set; }
    ushort? Slider2Type { get; set; }
    short? SlugOrSlap { get; set; }
    short? SmallBall { get; set; }
    ushort? SpecialSavedNameId { get; set; }
    short? Spin { get; set; }
    ushort? Stamina { get; set; }
    short? Stealing { get; set; }
    ushort? ThirdBaseCapability { get; set; }
    short? Throwing { get; set; }
    bool? ThrowsLefty { get; set; }
    ushort? TopThrowingSpeedKMH { get; set; }
    ushort? Trajectory { get; set; }
    ushort? TwoSeamMovement { get; set; }
    ushort? TwoSeamType { get; set; }
    bool? Unedited { get; set; }
    byte[]? UnknownByte_6b { get; set; }
    byte[]? UnknownByte_87 { get; set; }
    byte[]? UnknownBytes_81_83 { get; set; }
    byte[]? UnknownBytes_8d_92 { get; set; }
    ushort? VoiceId { get; set; }
    ushort? WalkoffHitter { get; set; }
    bool? WillBreakupDoublePlay { get; set; }
    bool? WillSlideHeadFirst { get; set; }
    short? WithRunnersInScoringPosition { get; set; }
    ushort? YearsInMajors { get; set; }
  }
}