name: Build and Package For Mac
on: 
  pull_request:
    types:
      - closed  
      
jobs:
  Build-and-Package:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest
      
    steps:
    - name: Get Current Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: -4
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core 6.0.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Install .NET Core 5.0.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Install ElectronNET CLI
      run: dotnet tool install --global ElectronNET.CLI --version 13.5.1
        
    - name: Install Powershell
      run: dotnet tool install --global PowerShell
           
    - name: Build  
      run: cd ./PowerUp/PowerUp.ElectronUI; 
           pwsh ./macPack.ps1;
        
    - name: Publish
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.time.outputs.time }}-osx
        path: ./PowerUp/PowerUp.ElectronUI/bin/Desktop
