name: Publish Electron Forge App (macOS)

on:
  release:
    types: [created]  # Runs when a new GitHub release is created

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Make macOS Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run make  # Runs Electron Forge 'make' command

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mac-build
          path: out/make/  # Path where Electron Forge saves the DMG file

      - name: Publish Release to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish  # Runs Electron Forge 'publish' command
